### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by gunshi** [dorian3d/DBoW2#12]
OSX : 10.11.12

-output of    cmake .. -DCMAKE_BUILD_TYPE=Release

> -- The C compiler identification is AppleClang 7.0.2.7000181
> -- The CXX compiler identification is AppleClang 7.0.2.7000181
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> CMake Warning (dev):
>   Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
>   --help-policy CMP0042" for policy details.  Use the cmake_policy command to
>   set the policy and suppress this warning.
> 
>   MACOSX_RPATH is not specified for the following targets:
> 
>    DBoW2
> 
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Generating done
> -- Build files have been written to: /Users/gunshigupta/Desktop/4sfm/ORB_SLAM/ThirdParty/DBoW2/build

-output of   make

> Scanning dependencies of target DBoW2
> [ 14%] Building CXX object CMakeFiles/DBoW2.dir/DBoW2/BowVector.cpp.o
> [ 28%] Building CXX object CMakeFiles/DBoW2.dir/DBoW2/FORB.cpp.o
> /Users/gunshigupta/Desktop/4sfm/ORB_SLAM/ThirdParty/DBoW2/DBoW2/FORB.cpp:16:10: fatal error: 
>       'stdint-gcc.h' file not found
> #include <stdint-gcc.h>
>          ^
> 1 error generated.
> make[2]: *** [CMakeFiles/DBoW2.dir/DBoW2/FORB.cpp.o] Error 1
> make[1]: *** [CMakeFiles/DBoW2.dir/all] Error 2
> make: *** [all] Error 2

What do i change/add to compile successfully?
Thanks!

**Comment by mhsung** [comment]
In OSX, I just replaced 'stdint-gcc.h' with 'stdint.h' and it works.
