### ISSUE TITLE
Question Vocabulary file

### ISSUE THREAD

**Issue by RobertNNms** [dorian3d/DBoW2#15]
Hi,

1/ Can I build database without Vocabulary file ?
I have a crash. (Have you an example?)

2/ Is it possible to append the vocabulary file?
To be more precise, I have files that will be added in time (uploaded by users), and therefore I would like to avoid rebuilding the vocabulary file every time a file is added.

3/ Is it possible replace file database (yml) by a database (cf. MongoDB) ?

Thanks
Regards

**Comment by dorian3d** [comment]
Hi Ribert,
1) The database indexes images in their bow representation, so it's not possible to use it without a vocabulary.
2) My implementation does not deal with incremental vocabulary creation, so I'm afraid you have to recreate it if you want to update it. However, you can add images to a database that is based on a generic vocabulary.
3) The current implementation doesn't use any format other than the yml one. It's text-based (after unzipped if necessary), and the format is not difficult if you look at the source code. So you may want to write a script to convert to yml from other formats.

**Comment by RobertNNms** [comment]
Thanks for your response.

So, I modified "TemplatedDatabase.h" for customization the output (load, add), for write directly in the database, and add the possiblity to remove.
