### ISSUE TITLE
Does DBoW2 support SIFT feature?

### ISSUE THREAD

**Issue by skylook** [dorian3d/DBoW2#16]
I wonder if DBoW2 can do with image retrieval system, but it seems only support SURF and not SIFT.
So is it suitable for image retrieval system or just loop detection?
Thanks :)

**Comment by dorian3d** [comment]
It can support any feature type by providing some little code. The code is readily available for SURF (and others), with the FSurf64.h/cpp class. If your SIFTs are encoded as floats, the easiest way to support SIFT is by copying the FSurf64.h/cpp files and setting the `L` constant to the the SIFT descriptor length (probably 128).
