### ISSUE TITLE
opencv2/core.hpp file not found

### ISSUE THREAD

**Issue by emmanuelom** [dorian3d/DBoW2#24]
Hello everyone.

I am trying to compile the code using Qt in a Mac OS Yosemite, and at compilation time I have the problem of "opencv2 / core.hpp file not found".

Any idea about that. Thank you. :)

**Comment by gallonden** [comment]
I also have the problem. I find that it depends on your opencv path, it may be opencv2/core/core.hpp. similar problems for other head files

**Comment by dorian3d** [comment]
Should be fine if you use release v1.1 for OpenCV >= 3.1 and v1.0 otherwise.
