### ISSUE TITLE
Issue in cmake while building in MSVC 2015

### ISSUE THREAD

**Issue by arunabhcode** [dorian3d/DBoW2#26]
Hi there is an error in compilation while trying to compile in MSVC 2015

**Issue:**

LNK 1181: Unable to link to Release\DBoW2.lib

**Suggested Resolution:**

changing
add_library(${PROJECT_NAME} SHARED ${SRCS})
to
add_library(${PROJECT_NAME} STATIC ${SRCS})

**Comment by dorian3d** [comment]
Thanks @arunabhcode
