### ISSUE TITLE
DLib error in installation

### ISSUE THREAD

**Issue by nabergh** [dorian3d/DBoW2#4]
When building with cmake I get the following error:

CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "FindDLib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DLib", but
  CMake did not find one.

  Could not find a package configuration file provided by "DLib" with any of
  the following names:

    DLibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "DLib" to CMAKE_PREFIX_PATH or set
  "DLib_DIR" to a directory containing one of the above files.  If "DLib"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by dorian3d** [comment]
Please, install DLib before building DBoW2. DLib is one of my libraries with some generic functions. You can find it here: https://github.com/dorian3d/DLib
I realized it's not listed as a dependency, my apologies, I'll update the documentation. Thank you.

**Comment by LiliMeng** [comment]
Thanks a lot! How shall I change the CMakeLists.txt file in DBoW2 to add the DLib?

**Comment by LiliMeng** [comment]
Sloved! When compile the DLib, I forgot to use $sudo make install after $cmake ..
