### ISSUE TITLE
DLib error while installation in ubuntu 14.04

### ISSUE THREAD

**Issue by Fahimkh** [dorian3d/DBoW2#9]
Hello @dorian3d ,

I am getting this error in ubuntu 14.04

[  3%] Building CXX object CMakeFiles/DLib.dir/src/DVision/SurfSet.cpp.o
/home/faheem/My Research Project Data/DLib-master/src/DVision/SurfSet.cpp:29:42: fatal error: opencv2/nonfree/features2d.hpp: No such file or directory
 #include <opencv2/nonfree/features2d.hpp>
                                          ^
compilation terminated.
make[2]: *** [CMakeFiles/DLib.dir/src/DVision/SurfSet.cpp.o] Error 1
make[1]: *** [CMakeFiles/DLib.dir/all] Error 2
make: *** [all] Error 2

can you help me in this case

**Comment by dorian3d** [comment]
Hey @Fahimkh,
Latest OpenCV version changed some directory structure. The quickest fix is to change the few include directives that cause troubles in DLib/DBoW/etc. The correct include path depends on the OpenCV verison you use.

**Comment by LinHuican** [comment]
Hello @Fahimkh @dorian3d , I clone DBoW2 and Dlib in the same folder Projects.
To the Dlib:
cd ~/Projects/Dlib
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j
Everything gose well
Then, To the DBoW2:
cd ~/Projects/DBoW2
mkdir build 
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..

Here, 
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "FindDLib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DLib", but
  CMake did not find one.

  Could not find a package configuration file provided by "DLib" with any of
  the following names:

    DLibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "DLib" to CMAKE_PREFIX_PATH or set
  "DLib_DIR" to a directory containing one of the above files.  If "DLib"
  provides a separate development package or SDK, be sure it has been
  installed.

Could you help me how to solve the problem?
Thank you for your help!

**Comment by kingsleynuaa** [comment]
I used opencv2.4.9 and DLib for Kintinuous as https://github.com/mp3guy/Kintinuous/blob/master/build.sh
but there are some problems when doing the command "make -j8"  in line 80.

I want to know how this error happen? 
there are some complier problem like this: 
/home/kingsley/workspace/Kintinuous/deps/DLib/src/DVision/Matches.cpp:14:28: fatal error: opencv2/core.hpp: No such file or directory
 #include <opencv2/core.hpp>

I guess this may be the problem of version, and another problem maybe the syntax problem: 
In file included from /home/kingsley/workspace/Kintinuous/deps/DLib/src/DVision/ImageFunctions.cpp:13:0:
/home/kingsley/workspace/Kintinuous/deps/DLib/include/DVision/ImageFunctions.h:38:52: error: ‘KeyPoint’ in namespace ‘cv’ does not name a type
   static cv::Mat getPatch(const cv::Mat &im, const cv::KeyPoint &kp,

I don't know if the problems may exist in the next two library: DBoW2, DLoopDetector
or I should change the version of opencv.

Thanks very much for your help, My operating system version is Ubuntu 14.04 x64
Thank you~

**Comment by dorian3d** [comment]
Last version expects OpenCV 3 at least. You can try fixing the include directives, though, see https://github.com/dorian3d/DLib/issues/7
